-   id: flakehell
    name: flakehell
    description: '`flakehell` is `flake8` wrapper to make a nice, legacy-friendly, configurable command-line utility for enforcing style consistency across Python projects.'
    entry: flakehell lint
    language: python
    types: [python]
    require_serial: true
