# Config for Travis CI, tests powered by DepHell.
# https://travis-ci.org/
# https://github.com/dephell/dephell

language: python
dist: xenial

# do not run Travis for PR's twice (as for push and as for PR)
branches:
  only:
    - master

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  # install DepHell
  - curl -L dephell.org/install > install.py
  - /opt/python/3.7.1/bin/python install.py --branch=master
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python"
  - dephell deps install --env=$ENV
  - dephell project register
script:
  - dephell venv run --env=$ENV

matrix:
  include:

    - python: "3.6.7"
      env: ENV=pytest
    - python: "3.7"
      env: ENV=pytest
    - python: "3.8"
      env: ENV=pytest

    - name: lint
      python: "3.7"
      env: ENV=main
    - python: "3.7"
      env: ENV=typing

    # https://github.com/igorshubovych/markdownlint-cli
    - name: markdown lint
      language: node_js
      node_js: "14"
      before_install:
        - true
      install:
        - npm install -g markdownlint-cli
      script:
        - bash -c "markdownlint --config markdownlint.json **/*.md"

    - python: "3.7"
      env: ENV=docs
