[tool.flakehell]
format = "colored"
max_line_length = 120
# show_source = true

[tool.flakehell.plugins]
"*" = ["+*", "-C408", "-C101"]
"flake8-quotes" = ["+*"]
"wemake-*" = ["+*", "-WPS300", "-WPS436"]
